### PR TITLE
Multi engine maven

### PR DESCRIPTION
**Pull request by nicolascouvrat**
Add a multi-engine example for maven.
The only thing to note here is that Junit5 *must* be 5.6.1 and up, see https://github.com/jlink/jqwik/issues/109.

---

I hereby agree to the terms of the [jqwik Contributor Agreement](https://github.com/jlink/jqwik/blob/master/CONTRIBUTING.md#jqwik-contributor-agreement).

### CODE REVIEW

**Comment by jlink** [comment]
Looks good. Thanks a lot!

I just added a [pull request template](https://github.com/jlink/jqwik-samples/blob/master/.github/PULL_REQUEST_TEMPLATE.md) which you do not have to fill in in retrospective but I need you to add the following clause to your PR description:

```
---

I hereby agree to the terms of the [jqwik Contributor Agreement](https://github.com/jlink/jqwik/blob/master/CONTRIBUTING.md#jqwik-contributor-agreement).
```

Then I can merge the PR.

**Comment by jlink** [comment]
@nicolascouvrat Any news on that?

**Comment by nicolascouvrat** [comment]
Hi there! Currently off for the week end, I’ll fix this next week.

Have a good Sunday :)

**Comment by nicolascouvrat** [comment]
Done!

**Comment by jlink** [comment]
Many thanks!

**Pull request merged**
